

# This is a basic workflow that is manually triggered

name: Deploy Manual

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}                                                                                               
      RELEASE_IMAGE: 7011347758/test:${{ github.sha }}

    steps:
    # This step instructs Github to cancel any current run for this job on this very repository.
  #  - name: Cancel Previous Runs               
    #  uses: styfle/cancel-workflow-action@0.4.1
    #  with:                                    
     #   access_token: ${{ github.token }}   
    - uses: actions/checkout@v2
    



#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#           username: ${{ secrets.DOCKER_USER }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
          
      
      
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5.8
      with:
          image: 7011347758/test
          tags: $RELEASE_IMAGE
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Deploy to Kubernetes cluster                                                                            
      uses: kodermax/kubectl-aws-eks@master                   
      with:                                                                                                         
        args: set image deployment/ecomm-app app=${{ env.RELEASE_IMAGE }} --record  
